SMALL_VILLA_TEMPLATE = {
  "Living Room": [
    {"key":"sofa", "name":"Sofa (dimensions + upholstery code + leg finish)", "category":"Furniture", "qty":1},
    {"key":"accent_chair", "name":"Accent chair (fabric/leather code + finish)", "category":"Furniture", "qty":2},
    {"key":"coffee_table", "name":"Coffee table (size + top material + base finish)", "category":"Furniture", "qty":1},
    {"key":"media_console", "name":"Media console (width + finish + cable management)", "category":"Furniture", "qty":1},
    {"key":"area_rug", "name":"Area rug (exact size + pile + colorway)", "category":"Furniture", "qty":1},
    {"key":"window_treatment", "name":"Curtains/blinds (fabric code + openness + track type)", "category":"Finish", "qty":1},
    {"key":"main_light", "name":"Main pendant/chandelier (diameter + drop + finish + lumen)", "category":"Lighting", "qty":1},
    {"key":"accent_wall_light", "name":"Wall sconces (IP rating if near glazing + finish)", "category":"Lighting", "qty":2},
    {"key":"switch_dimmer", "name":"Switches/dimmers (plate color + gang type)", "category":"Hardware", "qty":2},
    {"key":"wall_paint", "name":"Wall paint (brand + color code + sheen)", "category":"Finish", "qty":1},
    {"key":"floor_finish", "name":"Floor finish (material + size/plank + grout/joint spec)", "category":"Finish", "qty":1},
  ],
  "Kitchen": [
    {"key":"base_cabinetry", "name":"Base cabinetry (carcass spec + door finish + internal accessories)", "category":"Finish", "qty":1},
    {"key":"tall_cabinetry", "name":"Tall cabinetry/pantry (module widths + finish)", "category":"Finish", "qty":1},
    {"key":"cabinet_handles", "name":"Cabinet handles/pulls (model + finish + hole spacing)", "category":"Hardware", "qty":12},
    {"key":"countertop", "name":"Countertop slab (material + thickness + edge profile)", "category":"Finish", "qty":1},
    {"key":"backsplash", "name":"Backsplash tile/stone (tile size + layout + grout color)", "category":"Finish", "qty":1},
    {"key":"sink", "name":"Kitchen sink (mount type + bowl config + size)", "category":"Fixture", "qty":1},
    {"key":"faucet", "name":"Kitchen faucet (model + finish + pull-out/pull-down)", "category":"Fixture", "qty":1},
    {"key":"cooktop", "name":"Cooktop/hob (fuel type + model + power requirements)", "category":"Appliance", "qty":1},
    {"key":"oven", "name":"Built-in oven (model + niche dimensions)", "category":"Appliance", "qty":1},
    {"key":"hood", "name":"Extractor hood (airflow + ducting direction + finish)", "category":"Appliance", "qty":1},
    {"key":"undercabinet_light", "name":"Under-cabinet LED strip (CCT + driver + length)", "category":"Lighting", "qty":2},
    {"key":"main_light", "name":"Main kitchen light (lumen target + CRI + dimming)", "category":"Lighting", "qty":1},
    {"key":"backsplash_outlets", "name":"Counter outlets (count + location + plate finish)", "category":"Hardware", "qty":6},
  ],
  "Master Bedroom": [
    {"key":"bed_frame", "name":"Bed frame/headboard (size + upholstery/veneer code)", "category":"Furniture", "qty":1},
    {"key":"mattress", "name":"Mattress (size + firmness + thickness)", "category":"Furniture", "qty":1},
    {"key":"bedside_table", "name":"Bedside table (model + finish)", "category":"Furniture", "qty":2},
    {"key":"bedside_light", "name":"Bedside lamp/sconce (switch type + finish)", "category":"Lighting", "qty":2},
    {"key":"wardrobe", "name":"Wardrobe system (module plan + finish + handles)", "category":"Furniture", "qty":1},
    {"key":"dresser", "name":"Dresser/console (size + finish)", "category":"Furniture", "qty":1},
    {"key":"window_treatment", "name":"Blackout curtains/blinds (fabric code + lining)", "category":"Finish", "qty":1},
    {"key":"area_rug", "name":"Area rug (size + material + edge binding)", "category":"Furniture", "qty":1},
    {"key":"main_light", "name":"Main bedroom light (diameter + drop + CCT)", "category":"Lighting", "qty":1},
    {"key":"switch_dimmer", "name":"Switches/dimmers (location + plate finish)", "category":"Hardware", "qty":2},
    {"key":"wall_paint", "name":"Wall paint/wallcovering (brand + code + finish)", "category":"Finish", "qty":1},
    {"key":"floor_finish", "name":"Floor finish (material + plank/tile size + underlay)", "category":"Finish", "qty":1},
  ],
  "Bathroom": [
    {"key":"toilet", "name":"Toilet (wall-hung/floor + flush plate model)", "category":"Fixture", "qty":1},
    {"key":"vanity", "name":"Vanity cabinet (width + finish + storage layout)", "category":"Fixture", "qty":1},
    {"key":"basin", "name":"Basin/sink (mount type + dimensions)", "category":"Fixture", "qty":1},
    {"key":"faucet", "name":"Basin faucet (model + finish + mixer type)", "category":"Fixture", "qty":1},
    {"key":"shower_set", "name":"Shower set (rain head + hand shower + mixer spec)", "category":"Fixture", "qty":1},
    {"key":"shower_glass", "name":"Shower glass partition (clear/frosted + hardware finish)", "category":"Fixture", "qty":1},
    {"key":"mirror", "name":"Mirror/medicine cabinet (size + anti-fog + lighting)", "category":"Fixture", "qty":1},
    {"key":"towel_hardware", "name":"Towel rails/hooks (set + finish)", "category":"Hardware", "qty":3},
    {"key":"floor_drain", "name":"Floor drain/trap (type + finish)", "category":"Fixture", "qty":1},
    {"key":"wall_tile", "name":"Wall tile/stone (size + layout + grout color)", "category":"Finish", "qty":1},
    {"key":"floor_tile", "name":"Floor tile/stone (anti-slip rating + grout)", "category":"Finish", "qty":1},
    {"key":"ceiling_light", "name":"Ceiling light (IP rating + lumen + CCT)", "category":"Lighting", "qty":1},
  ],
  "Outdoor / Terrace": [
    {"key":"outdoor_table", "name":"Outdoor dining table (material + weather rating)", "category":"Furniture", "qty":1},
    {"key":"outdoor_chairs", "name":"Outdoor chairs (material + cushion fabric code)", "category":"Furniture", "qty":6},
    {"key":"lounge_set", "name":"Lounge seating set (configuration + upholstery code)", "category":"Furniture", "qty":1},
    {"key":"side_table", "name":"Outdoor side table (size + finish)", "category":"Furniture", "qty":2},
    {"key":"outdoor_wall_light", "name":"Outdoor wall lights (IP rating + finish + beam)", "category":"Lighting", "qty":2},
    {"key":"outdoor_floor_light", "name":"Step/floor lights (IP rating + spacing)", "category":"Lighting", "qty":4},
    {"key":"deck_finish", "name":"Deck/paver finish (material + board/tile size + installation)", "category":"Finish", "qty":1},
    {"key":"planter", "name":"Planters (size + material + drain requirement)", "category":"Furniture", "qty":4},
    {"key":"shade_system", "name":"Pergola/awning shade system (model + fabric code)", "category":"Fixture", "qty":1},
    {"key":"weatherproof_outlet", "name":"Weatherproof outlets (count + location + cover type)", "category":"Hardware", "qty":2},
  ]
}
