def _clone(items):
    return [dict(x) for x in items]


_BEDROOM_BASE = [
    {"key": "bed_frame", "name": "Bed frame/headboard (size + finish)", "category": "Furniture", "qty": 1},
    {"key": "mattress", "name": "Mattress (size + firmness)", "category": "Furniture", "qty": 1},
    {"key": "bedside_table", "name": "Bedside table (model + finish)", "category": "Furniture", "qty": 2},
    {"key": "wardrobe", "name": "Wardrobe (layout + finish + handles)", "category": "Furniture", "qty": 1},
    {"key": "window_treatment", "name": "Curtains/blinds (fabric code + blackout)", "category": "Finish", "qty": 1},
    {"key": "main_light", "name": "Main light (lumen + CCT + finish)", "category": "Lighting", "qty": 1},
    {"key": "bedside_light", "name": "Bedside lamp/sconce (switch + finish)", "category": "Lighting", "qty": 2},
    {"key": "wall_paint", "name": "Wall finish (paint/wallcovering + code)", "category": "Finish", "qty": 1},
    {"key": "floor_finish", "name": "Floor finish (material + size + underlay)", "category": "Finish", "qty": 1},
]

_BATHROOM_BASE = [
    {"key": "toilet", "name": "Toilet (type + flush plate)", "category": "Fixture", "qty": 1},
    {"key": "vanity", "name": "Vanity cabinet (width + finish)", "category": "Fixture", "qty": 1},
    {"key": "basin", "name": "Basin (mount type + dimensions)", "category": "Fixture", "qty": 1},
    {"key": "faucet", "name": "Basin faucet (model + finish)", "category": "Fixture", "qty": 1},
    {"key": "shower_set", "name": "Shower set (rain head + mixer spec)", "category": "Fixture", "qty": 1},
    {"key": "mirror", "name": "Mirror/cabinet (size + anti-fog option)", "category": "Fixture", "qty": 1},
    {"key": "towel_hardware", "name": "Towel rails/hooks (set + finish)", "category": "Hardware", "qty": 3},
    {"key": "wall_tile", "name": "Wall tile/stone (size + layout + grout)", "category": "Finish", "qty": 1},
    {"key": "floor_tile", "name": "Floor tile/stone (anti-slip + grout)", "category": "Finish", "qty": 1},
    {"key": "ceiling_light", "name": "Ceiling light (IP rating + CCT)", "category": "Lighting", "qty": 1},
]

_OUTDOOR_BASE = [
    {"key": "outdoor_table", "name": "Outdoor table (material + weather rating)", "category": "Furniture", "qty": 1},
    {"key": "outdoor_chairs", "name": "Outdoor chairs (material + fabric code)", "category": "Furniture", "qty": 4},
    {"key": "side_table", "name": "Side table (size + finish)", "category": "Furniture", "qty": 2},
    {"key": "outdoor_light", "name": "Outdoor lights (IP rating + finish)", "category": "Lighting", "qty": 3},
    {"key": "weatherproof_outlet", "name": "Weatherproof outlets (count + location)", "category": "Hardware", "qty": 2},
    {"key": "floor_finish", "name": "Deck/paver finish (material + anti-slip)", "category": "Finish", "qty": 1},
]


SMALL_VILLA_TEMPLATE = {
    "Living Room": [
        {"key": "sofa", "name": "Sofa (size + upholstery code + finish)", "category": "Furniture", "qty": 1},
        {"key": "accent_chair", "name": "Accent chair (fabric/leather + finish)", "category": "Furniture", "qty": 2},
        {"key": "coffee_table", "name": "Coffee table (size + top/base material)", "category": "Furniture", "qty": 1},
        {"key": "media_console", "name": "Media console (width + finish + cable mgmt)", "category": "Furniture", "qty": 1},
        {"key": "area_rug", "name": "Area rug (size + pile + colorway)", "category": "Furniture", "qty": 1},
        {"key": "window_treatment", "name": "Curtains/blinds (fabric code + track)", "category": "Finish", "qty": 1},
        {"key": "main_light", "name": "Main light fixture (size + lumen + finish)", "category": "Lighting", "qty": 1},
        {"key": "accent_wall_light", "name": "Wall sconces (model + finish)", "category": "Lighting", "qty": 2},
        {"key": "switch_dimmer", "name": "Switches/dimmers (plate + gang type)", "category": "Hardware", "qty": 2},
        {"key": "wall_paint", "name": "Wall paint/wallcovering (brand + color code)", "category": "Finish", "qty": 1},
        {"key": "floor_finish", "name": "Floor finish (material + size + joint spec)", "category": "Finish", "qty": 1},
    ],
    "Kitchen": [
        {"key": "base_cabinetry", "name": "Base cabinetry (carcass + door finish)", "category": "Finish", "qty": 1},
        {"key": "tall_cabinetry", "name": "Tall cabinetry/pantry (module widths)", "category": "Finish", "qty": 1},
        {"key": "cabinet_handles", "name": "Cabinet handles/pulls (model + finish)", "category": "Hardware", "qty": 14},
        {"key": "countertop", "name": "Countertop slab (material + thickness + edge)", "category": "Finish", "qty": 1},
        {"key": "backsplash", "name": "Backsplash (tile/stone + layout + grout)", "category": "Finish", "qty": 1},
        {"key": "sink", "name": "Kitchen sink (mount type + bowl config)", "category": "Fixture", "qty": 1},
        {"key": "faucet", "name": "Kitchen faucet (model + finish + type)", "category": "Fixture", "qty": 1},
        {"key": "cooktop", "name": "Cooktop/hob (fuel type + model)", "category": "Appliance", "qty": 1},
        {"key": "oven", "name": "Built-in oven (model + niche dims)", "category": "Appliance", "qty": 1},
        {"key": "hood", "name": "Extractor hood (airflow + ducting + finish)", "category": "Appliance", "qty": 1},
        {"key": "dishwasher", "name": "Dishwasher (integrated/freestanding)", "category": "Appliance", "qty": 1},
        {"key": "fridge", "name": "Fridge (capacity + door config + finish)", "category": "Appliance", "qty": 1},
        {"key": "undercabinet_light", "name": "Under-cabinet LED strip (CCT + driver)", "category": "Lighting", "qty": 2},
        {"key": "main_light", "name": "Main light (lumen target + CRI + dimming)", "category": "Lighting", "qty": 1},
        {"key": "backsplash_outlets", "name": "Counter outlets (count + location + plate)", "category": "Hardware", "qty": 6},
    ],
    "Dining Room": [
        {"key": "dining_table", "name": "Dining table (size + top/base finish)", "category": "Furniture", "qty": 1},
        {"key": "dining_chair", "name": "Dining chairs (upholstery code + finish)", "category": "Furniture", "qty": 6},
        {"key": "sideboard", "name": "Sideboard/buffet (length + finish)", "category": "Furniture", "qty": 1},
        {"key": "area_rug", "name": "Area rug (size + material + colorway)", "category": "Furniture", "qty": 1},
        {"key": "main_pendant", "name": "Pendant/chandelier (size + drop + lumen)", "category": "Lighting", "qty": 1},
        {"key": "accent_light", "name": "Accent wall light (model + finish)", "category": "Lighting", "qty": 2},
        {"key": "window_treatment", "name": "Curtains/blinds (fabric code + track)", "category": "Finish", "qty": 1},
        {"key": "switch_dimmer", "name": "Switches/dimmers (plate + gang type)", "category": "Hardware", "qty": 2},
        {"key": "wall_paint", "name": "Wall paint/wallcovering (brand + code)", "category": "Finish", "qty": 1},
        {"key": "floor_finish", "name": "Floor finish (material + size + joint spec)", "category": "Finish", "qty": 1},
    ],
    "Bedroom": _clone(_BEDROOM_BASE),
    "Master Bedroom": _clone(_BEDROOM_BASE) + [
        {"key": "lounge_chair", "name": "Lounge chair/ottoman (fabric + finish)", "category": "Furniture", "qty": 1},
        {"key": "dresser", "name": "Dresser/console (size + finish)", "category": "Furniture", "qty": 1},
        {"key": "tv_console", "name": "TV console (width + finish + cable mgmt)", "category": "Furniture", "qty": 1},
    ],
    "Guest Bedroom": _clone(_BEDROOM_BASE) + [
        {"key": "desk", "name": "Desk/console (size + finish)", "category": "Furniture", "qty": 1},
        {"key": "chair", "name": "Desk chair (fabric + finish)", "category": "Furniture", "qty": 1},
    ],
    "Bathroom": _clone(_BATHROOM_BASE),
    "Guest Bathroom": _clone(_BATHROOM_BASE) + [
        {"key": "shower_glass", "name": "Shower glass partition (clear/frosted + finish)", "category": "Fixture", "qty": 1},
    ],
    "Outdoor / Terrace": _clone(_OUTDOOR_BASE) + [
        {"key": "lounge_set", "name": "Lounge seating set (config + fabric code)", "category": "Furniture", "qty": 1},
        {"key": "shade_system", "name": "Pergola/awning (model + fabric code)", "category": "Fixture", "qty": 1},
        {"key": "planter", "name": "Planters (size + material + drainage)", "category": "Furniture", "qty": 4},
    ],
    "Garden": [
        {"key": "softscape_planting", "name": "Planting palette (species + density + maturity)", "category": "Finish", "qty": 1},
        {"key": "trees", "name": "Feature trees (species + trunk size)", "category": "Finish", "qty": 2},
        {"key": "lawn_or_groundcover", "name": "Lawn/groundcover (type + area)", "category": "Finish", "qty": 1},
        {"key": "hardscape_path", "name": "Pathway paving (material + format + joint fill)", "category": "Finish", "qty": 1},
        {"key": "irrigation_system", "name": "Irrigation (zones + emitters + controller)", "category": "Fixture", "qty": 1},
        {"key": "drainage", "name": "Garden drainage (channel/catch basin)", "category": "Fixture", "qty": 1},
        {"key": "boundary_fence", "name": "Boundary fence/screen (material + height)", "category": "Hardware", "qty": 1},
        {"key": "garden_bench", "name": "Garden bench (material + weather rating)", "category": "Furniture", "qty": 1},
        {"key": "path_lights", "name": "Path/bollard lights (IP + spacing + CCT)", "category": "Lighting", "qty": 6},
        {"key": "feature_uplight", "name": "Feature uplights (beam + wattage + finish)", "category": "Lighting", "qty": 4},
    ],
    "Balcony": _clone(_OUTDOOR_BASE) + [
        {"key": "bistro_table", "name": "Bistro table (size + weather rating)", "category": "Furniture", "qty": 1},
        {"key": "bistro_chairs", "name": "Bistro chairs (material + cushion code)", "category": "Furniture", "qty": 2},
        {"key": "railing", "name": "Balcony railing (glass/metal + finish + height)", "category": "Hardware", "qty": 1},
    ],
    "Pool Area": [
        {"key": "pool_finish", "name": "Pool interior finish (tile/plaster + color)", "category": "Finish", "qty": 1},
        {"key": "pool_coping", "name": "Pool coping (material + edge profile)", "category": "Finish", "qty": 1},
        {"key": "pool_deck", "name": "Pool deck (material + anti-slip + joint spec)", "category": "Finish", "qty": 1},
        {"key": "sun_lounger", "name": "Sun loungers (material + fabric code)", "category": "Furniture", "qty": 4},
        {"key": "shade_umbrella", "name": "Umbrella/pergola shade (size + fabric code)", "category": "Furniture", "qty": 2},
        {"key": "pool_side_table", "name": "Pool side tables (size + weather rating)", "category": "Furniture", "qty": 2},
        {"key": "outdoor_shower", "name": "Outdoor shower set (model + finish)", "category": "Fixture", "qty": 1},
        {"key": "pool_equipment", "name": "Pool equipment (pump + filter + treatment)", "category": "Appliance", "qty": 1},
        {"key": "pool_lights", "name": "Underwater lights (wattage + CCT/RGB)", "category": "Lighting", "qty": 4},
        {"key": "area_lighting", "name": "Perimeter/path lighting (IP + spacing)", "category": "Lighting", "qty": 6},
    ],
    "Entrance": [
        {"key": "main_door", "name": "Main door (material + hardware + security)", "category": "Hardware", "qty": 1},
        {"key": "smart_lock", "name": "Smart lock/intercom (model + access method)", "category": "Hardware", "qty": 1},
        {"key": "console_table", "name": "Console table (size + finish)", "category": "Furniture", "qty": 1},
        {"key": "entry_bench", "name": "Entry bench (size + upholstery + finish)", "category": "Furniture", "qty": 1},
        {"key": "mirror", "name": "Entrance mirror (size + frame finish)", "category": "Furniture", "qty": 1},
        {"key": "coat_hooks", "name": "Coat hooks/rail (count + finish)", "category": "Hardware", "qty": 1},
        {"key": "shoe_storage", "name": "Shoe cabinet (width + finish + ventilation)", "category": "Furniture", "qty": 1},
        {"key": "main_light", "name": "Ceiling light (lumen + CCT + finish)", "category": "Lighting", "qty": 1},
        {"key": "wall_light", "name": "Wall lights (model + finish)", "category": "Lighting", "qty": 2},
        {"key": "wall_finish", "name": "Wall finish (paint/panel + color code)", "category": "Finish", "qty": 1},
        {"key": "floor_finish", "name": "Floor finish (tile/stone/wood + anti-slip)", "category": "Finish", "qty": 1},
    ],
    "Walk-in Closet": [
        {"key": "closet_system", "name": "Closet system (hanging + shelves + drawers)", "category": "Furniture", "qty": 1},
        {"key": "island_unit", "name": "Closet island/dresser (size + finish)", "category": "Furniture", "qty": 1},
        {"key": "drawer_organizers", "name": "Drawer organizers (jewelry/watch/tie)", "category": "Furniture", "qty": 1},
        {"key": "full_length_mirror", "name": "Full-length mirror (size + frame detail)", "category": "Furniture", "qty": 1},
        {"key": "bench", "name": "Ottoman/bench seating (fabric + finish)", "category": "Furniture", "qty": 1},
        {"key": "pull_down_rails", "name": "Pull-down rails/accessories (model + finish)", "category": "Hardware", "qty": 2},
        {"key": "led_strip", "name": "Integrated LED strips (CCT + driver + sensor)", "category": "Lighting", "qty": 4},
        {"key": "ceiling_light", "name": "Ceiling light (lumen + CRI + dimming)", "category": "Lighting", "qty": 1},
        {"key": "switch_sensor", "name": "Switches/sensors (plate + automation mode)", "category": "Hardware", "qty": 2},
        {"key": "floor_finish", "name": "Floor finish (material + size + underlay)", "category": "Finish", "qty": 1},
    ],
    "Pantry": [
        {"key": "shelving_system", "name": "Shelving system (module depth + load rating)", "category": "Furniture", "qty": 1},
        {"key": "storage_bins", "name": "Storage bins/containers (set + labels)", "category": "Furniture", "qty": 1},
        {"key": "countertop", "name": "Prep counter (material + thickness + edge)", "category": "Finish", "qty": 1},
        {"key": "tall_cabinet", "name": "Tall cabinet (door finish + pull-outs)", "category": "Furniture", "qty": 1},
        {"key": "small_appliance_station", "name": "Appliance station (niche + outlets)", "category": "Appliance", "qty": 1},
        {"key": "pull_out_baskets", "name": "Pull-out baskets/trays (size + quantity)", "category": "Hardware", "qty": 4},
        {"key": "task_light", "name": "Task lighting (LED/ceiling + CCT + lumen)", "category": "Lighting", "qty": 2},
        {"key": "outlets", "name": "Power outlets (count + location + plate)", "category": "Hardware", "qty": 3},
        {"key": "floor_finish", "name": "Floor finish (tile/vinyl + anti-slip)", "category": "Finish", "qty": 1},
    ],
    "Laundry Room": [
        {"key": "washing_machine", "name": "Washing machine (capacity + model)", "category": "Appliance", "qty": 1},
        {"key": "dryer", "name": "Dryer (vented/heat pump + model)", "category": "Appliance", "qty": 1},
        {"key": "laundry_sink", "name": "Laundry sink + faucet (size + finish)", "category": "Fixture", "qty": 1},
        {"key": "countertop", "name": "Folding counter (material + thickness)", "category": "Finish", "qty": 1},
        {"key": "base_cabinetry", "name": "Base cabinetry (finish + accessories)", "category": "Furniture", "qty": 1},
        {"key": "wall_cabinetry", "name": "Wall cabinetry/shelves (widths + finish)", "category": "Furniture", "qty": 1},
        {"key": "hanging_rail", "name": "Hanging rail/drying rack (type + length)", "category": "Hardware", "qty": 1},
        {"key": "floor_drain", "name": "Floor drain/trap (type + finish)", "category": "Fixture", "qty": 1},
        {"key": "task_light", "name": "Task/ceiling light (lumen + CCT)", "category": "Lighting", "qty": 2},
        {"key": "outlets", "name": "Dedicated outlets (count + location)", "category": "Hardware", "qty": 4},
        {"key": "wall_finish", "name": "Wall finish (paint/tile + code)", "category": "Finish", "qty": 1},
        {"key": "floor_finish", "name": "Floor finish (anti-slip + grout/joint)", "category": "Finish", "qty": 1},
    ],
    "Garage": [
        {"key": "garage_door", "name": "Garage door (sectional/roller + insulation)", "category": "Hardware", "qty": 1},
        {"key": "door_motor", "name": "Garage door motor/opener (model + control)", "category": "Appliance", "qty": 1},
        {"key": "ev_charger", "name": "EV charger (power + connector + mounting)", "category": "Appliance", "qty": 1},
        {"key": "storage_cabinets", "name": "Garage cabinets (module widths + finish)", "category": "Furniture", "qty": 1},
        {"key": "heavy_shelving", "name": "Heavy-duty shelves/racks (load + dimensions)", "category": "Furniture", "qty": 2},
        {"key": "workbench", "name": "Workbench (size + top material + finish)", "category": "Furniture", "qty": 1},
        {"key": "tool_board", "name": "Tool board/peg system (layout + accessory set)", "category": "Hardware", "qty": 1},
        {"key": "ceiling_light", "name": "Garage lights (lumen + CCT + spacing)", "category": "Lighting", "qty": 3},
        {"key": "outlets", "name": "Power outlets (count + amp mix + location)", "category": "Hardware", "qty": 4},
        {"key": "floor_finish", "name": "Garage floor finish (epoxy/tile + anti-slip)", "category": "Finish", "qty": 1},
    ],
    "Storage Room": [
        {"key": "shelving_system", "name": "Shelving system (depth + load rating)", "category": "Furniture", "qty": 2},
        {"key": "cabinet", "name": "Lockable cabinet (size + finish)", "category": "Furniture", "qty": 1},
        {"key": "storage_bins", "name": "Storage bins/boxes (set + labels)", "category": "Furniture", "qty": 1},
        {"key": "hanging_hooks", "name": "Wall hooks/hangers (count + finish)", "category": "Hardware", "qty": 8},
        {"key": "ceiling_light", "name": "Ceiling light (lumen + CCT)", "category": "Lighting", "qty": 1},
        {"key": "switch", "name": "Switch + outlet combo (plate finish)", "category": "Hardware", "qty": 1},
        {"key": "door_lockset", "name": "Door lockset (model + finish + privacy type)", "category": "Hardware", "qty": 1},
        {"key": "wall_finish", "name": "Wall finish (paint + color code)", "category": "Finish", "qty": 1},
        {"key": "floor_finish", "name": "Floor finish (tile/vinyl/epoxy + durability)", "category": "Finish", "qty": 1},
    ],
    "Office / Study": [
        {"key": "desk", "name": "Work desk (size + material + cable mgmt)", "category": "Furniture", "qty": 1},
        {"key": "task_chair", "name": "Task chair (ergonomic spec + upholstery)", "category": "Furniture", "qty": 1},
        {"key": "guest_chair", "name": "Guest chairs (model + finish)", "category": "Furniture", "qty": 2},
        {"key": "bookcase", "name": "Bookcase/storage unit (layout + finish)", "category": "Furniture", "qty": 1},
        {"key": "filing_storage", "name": "Filing cabinet (size + lock type)", "category": "Furniture", "qty": 1},
        {"key": "window_treatment", "name": "Curtains/blinds (glare control + fabric)", "category": "Finish", "qty": 1},
        {"key": "task_light", "name": "Desk/task light (CRI + CCT + dimming)", "category": "Lighting", "qty": 1},
        {"key": "ceiling_light", "name": "Ceiling light (lumen + UGR + CCT)", "category": "Lighting", "qty": 1},
        {"key": "data_power_points", "name": "Data/power points (count + position)", "category": "Hardware", "qty": 4},
        {"key": "wall_finish", "name": "Wall finish (paint/panel + color code)", "category": "Finish", "qty": 1},
        {"key": "floor_finish", "name": "Floor finish (wood/carpet + acoustic underlay)", "category": "Finish", "qty": 1},
    ],
    "Kids Room": [
        {"key": "bed_frame", "name": "Kids bed frame (size + guardrail + finish)", "category": "Furniture", "qty": 1},
        {"key": "mattress", "name": "Mattress (size + firmness)", "category": "Furniture", "qty": 1},
        {"key": "bedside_table", "name": "Bedside table (rounded edge + finish)", "category": "Furniture", "qty": 1},
        {"key": "wardrobe", "name": "Wardrobe (layout + child-safe handles)", "category": "Furniture", "qty": 1},
        {"key": "study_desk", "name": "Study desk (size + finish + cable access)", "category": "Furniture", "qty": 1},
        {"key": "study_chair", "name": "Study chair (height adjust + finish)", "category": "Furniture", "qty": 1},
        {"key": "toy_storage", "name": "Toy storage (bins + anti-tip anchors)", "category": "Furniture", "qty": 1},
        {"key": "window_treatment", "name": "Blackout blinds/curtains (child-safe control)", "category": "Finish", "qty": 1},
        {"key": "main_light", "name": "Main light (lumen + CCT + dimming)", "category": "Lighting", "qty": 1},
        {"key": "night_light", "name": "Night light (warm CCT + low glare)", "category": "Lighting", "qty": 1},
        {"key": "wall_finish", "name": "Wall finish (washable paint/wallpaper)", "category": "Finish", "qty": 1},
        {"key": "floor_finish", "name": "Floor finish (durable + soft underlay)", "category": "Finish", "qty": 1},
    ],
    "Play Area": [
        {"key": "play_mat", "name": "Play mat/soft flooring (material + thickness)", "category": "Finish", "qty": 1},
        {"key": "activity_table", "name": "Activity table (size + finish)", "category": "Furniture", "qty": 1},
        {"key": "small_chairs", "name": "Kids chairs/stools (material + finish)", "category": "Furniture", "qty": 4},
        {"key": "toy_shelves", "name": "Toy shelves/cubbies (sizes + anchoring)", "category": "Furniture", "qty": 1},
        {"key": "soft_seating", "name": "Soft seating/bean bags (fabric + filling)", "category": "Furniture", "qty": 2},
        {"key": "book_display", "name": "Book display (size + finish)", "category": "Furniture", "qty": 1},
        {"key": "safety_gate", "name": "Safety gate/partition (width + lock)", "category": "Hardware", "qty": 1},
        {"key": "ceiling_light", "name": "General lighting (lumen + CCT)", "category": "Lighting", "qty": 1},
        {"key": "accent_light", "name": "Accent/play lighting (type + control)", "category": "Lighting", "qty": 1},
        {"key": "wall_finish", "name": "Wall finish (washable paint/panel)", "category": "Finish", "qty": 1},
    ],
    "Hallway": [
        {"key": "console_table", "name": "Hallway console (size + finish)", "category": "Furniture", "qty": 1},
        {"key": "runner_rug", "name": "Runner rug (size + material + anti-slip)", "category": "Furniture", "qty": 1},
        {"key": "mirror", "name": "Mirror/art panel (size + frame finish)", "category": "Furniture", "qty": 1},
        {"key": "artwork", "name": "Artwork/framed pieces (size mix + mounting)", "category": "Furniture", "qty": 2},
        {"key": "wall_light", "name": "Wall sconces (model + finish + beam)", "category": "Lighting", "qty": 2},
        {"key": "ceiling_light", "name": "Ceiling/downlights (spacing + lumen + CCT)", "category": "Lighting", "qty": 4},
        {"key": "switches", "name": "Multi-way switches (plate + control points)", "category": "Hardware", "qty": 2},
        {"key": "wall_finish", "name": "Wall finish (paint/panel + color code)", "category": "Finish", "qty": 1},
        {"key": "floor_finish", "name": "Floor finish (material + transition profile)", "category": "Finish", "qty": 1},
        {"key": "skirting_trim", "name": "Skirting/trim (profile + finish)", "category": "Finish", "qty": 1},
    ],
}
